services:
  web:
    build:
      context: .
      target: $MODE
      args:
        - SECRET_KEY=$SECRET_KEY
    ports:
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock